### ISSUE TITLE
Help with attribution for tests

### ISSUE THREAD

**Issue by kulp** [briandfoy/mac-propertylist#11]
@briandfoy -- I am sorry for using an issue for this. I am happy to move this discussion elsewhere if helpful.

My question is: **how would you prefer your _test_ files to be attributed if I use them in [`Mac::PropertyList::SAX`](https://github.com/kulp/Mac-PropertyList-SAX)?**

I would like to use https://github.com/kulp/Mac-PropertyList-SAX/pull/4 to incorporate your improved tests, verbatim wherever possible, particularly covering functionality that was added to `Mac::PropertyList` since my implementation of `Mac::PropertyList::SAX`. As you may know, I have been using modified versions of them for years, with unfortunately-worded ["Stolen from ..." comments](https://github.com/kulp/Mac-PropertyList-SAX/pull/4/files#diff-f96fbcecc69668ce7e7ede86056cc72d1f39c7b0af7d0c66b2c73d751e5ee6d1L1), and I would like to do better.

I was thinking of including a [`README.md` file in the `t/` directory](https://github.com/kulp/Mac-PropertyList-SAX/pull/4/files#diff-ea1cf576d6af5497c99c07e86980795b200126085e5bbb0a3e30cfc95a9d512f) to point at your repository. Can you suggest better content for that file, or a different idea?

Since both your project and mine are licensed under the same terms as Perl (although mine only [says so in POD](https://github.com/kulp/Mac-PropertyList-SAX/blob/master/lib/Mac/PropertyList/SAX.pm#L525-L533), so far), I think this is a question more of good practice than of licensing per se, but please let me know your thoughts.

Thank you.

**Comment by briandfoy** [comment]
I think attribution in each file is probably the best. I can update the test files and then you can just copy them. It might take me a couple weeks to get to this though.

**Comment by kulp** [comment]
> I can update the test files and then you can just copy them.

Sure, that is fine with me. No rush; if you come up with a pattern you like and just put it here, I could also do insert a header myself.

**Comment by briandfoy** [comment]
I've uploaded new versions of the tests that have minimal docs and attribution. These should be suitable for you to import into your project.

I did something else for you, too. Rather than hardcoding the namespaces, I put them in variables then used those everywhere. In many cases, you should be able to update the single hardcoded namespace and everywhere else in the same file picks it up.

When you commit these, you can use `GIT_AUTHOR_NAME ` and `GIT_AUTHOR_EMAIL` (see [the docs on env vars](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)) so your repo credits the right people. There is also `GIT_COMMITTER_*`, which would be you (or whomever). There's one test where I'm not the original author, so something like this might work:

    env GIT_AUTHOR_NAME='Wim Lewis' GIT_AUTHOR_EMAIL='wiml@hhhh.org' t/write_binary.t
    env GIT_AUTHOR_NAME='brian d foy' GIT_AUTHOR_EMAIL='brian.d.foy@gmail.com' t/*.t

For what it's worth, I'd import the files as-is, and then in a separate pull request do the modifications that you need. But, whatever works for you.

**Comment by kulp** [comment]
@briandfoy thanks so much! I expect to follow the path you expected.

**Comment by kulp** [comment]
> For what it's worth, I'd import the files as-is, and then in a separate pull request do the modifications that you need. But, whatever works for you.

I ended up using [a merge commit](https://github.com/kulp/Mac-PropertyList-SAX/pull/5/commits/324b0dcc29c887e83d5b14bfdadd791bc6ca8887) within https://github.com/kulp/Mac-PropertyList-SAX/pull/5 to segregate the additions, so that my `master` branch did not see tests popping out of and into existence, while still showing the imports as direct additions.

Thanks again for working with me on this.
